-- REGISTROS TABLA MEDIOS_TECNICOS
INSERT INTO MEDIO_TECNICO (nombre) VALUES ('Presentacion');
INSERT INTO MEDIO_TECNICO (nombre) VALUES ('Megafonía');
INSERT INTO MEDIO_TECNICO (nombre) VALUES ('Grabación');
INSERT INTO MEDIO_TECNICO (nombre) VALUES ('Emisión en streaming');
INSERT INTO MEDIO_TECNICO (nombre) VALUES ('Wifi');

-- REGISTROS TABLA HORARIOS
INSERT INTO HORARIO (hinicio, hfinal) VALUES ('10:00:00', '12:00:00');
INSERT INTO HORARIO (hinicio, hfinal) VALUES ('11:00:00', '16:30:00');
INSERT INTO HORARIO (hinicio, hfinal) VALUES ('12:00:00', '14:00:00');

-- REGISTROS TABLA SALAS
INSERT INTO SALA (nombre, aforo) VALUES ('Sala 1', 4);
INSERT INTO SALA (nombre, aforo) VALUES ('Sala 2', 6);
INSERT INTO SALA (nombre, aforo) VALUES ('Sala 3', 8);
INSERT INTO SALA (nombre, aforo) VALUES ('Sala 4', 15);

INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (1, 1);
INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (1, 2);
INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (2, 1);
INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (2, 3);
INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (4, 2);
INSERT INTO SALA_LISTA_HORARIOS (sala_id, horario_id) VALUES (4, 3);

INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (1, 1);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (1, 2);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (2, 1);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (2, 5);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (3, 2);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (3, 3);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (3, 4);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (4, 1);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (4, 2);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (4, 3);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (4, 4);
INSERT INTO SALA_LISTA_MEDIOS_TECNICOS (sala_id, medio_id) VALUES (4, 5);